version: 2.1
jobs:
    build:
        working_directory:$work/src/github.com/kukku723/circleci-demo
        docker:
            - image: golang:1.11.4
        steps:
            - checkout
            - run:
                name: "run go code"
                command: |
                    go run main.go
            - run:
                name: Install GolangCI-Lint
                command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0
            - run:
                name: Run GolangCI-Lint
                command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck

#workflows:
#    golang-workflow:
#        jobs:
#            - build:
#                  go-version: "1.11.5"
#                  golangci-lint-version: "1.15.0"